[[constraint]]
  branch = "master"
  name = "github.com/rylio/ytdl"

[[constraint]]
  version = "^1.1.0"
  name = "github.com/shopspring/decimal"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "google.golang.org/api"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "^1.10.51"

[[constraint]]
  name = "github.com/lbryio/lbry.go"
  branch = "lbrynet-updates"
